---
title: "Mapping with R"
author: "Jeff Matheson"
date: "23/01/2020"
output:
  html_notebook:
    toc: TRUE
---

# Introduction

These are my notes and code snippets relating to creation of maps using r.

#### Reference Material:

<https://rstudio.github.io/leaflet/map_widget.html>

# Packages

```{r packages, echo=TRUE, message=FALSE, warning=FALSE}
library(sp)         ## Key package. Though being replaced by sf.
library(sf)         ## Replaces sp. sp still needed for some things.
library(rgdal)      ## Bindings for GDAL(?) seems to provide helper functions

library(raster)     ## This is key for raster manipulation.
library(rasterVis)
library(maptools)   ## Haven't used this yet

library(maps)

library(rgeos)      # ? Has some data. Geometry Engine
library(tmap)
library(tmaptools)
library(ggmap)      ## Spatial Visualization with ggplot2

## For dynamic map bases
library(leaflet)    # This is very popular. 
library(mapview)    # Another popular package for interactive maps

library(htmlwidgets)
library(shiny)
library(webshot)

## Other: 
library(sdm)        # species distribution modeling

```

# Some Basic Mapping Examples

```{r}
data("wrld_simpl")
plot(wrld_simpl)
data("canada_simpl")

tm_shape("wrld_simpl") + tm_borders()

map("worldHires","Canada”, xlim=c(-141,-53), ylim=c(40,85), col="gray90”, fill=TRUE))

```

# Leaflet

```{r}
## Leaflet

library(leaflet)    # This is very popular. 

m <- leaflet() %>% 
      addTiles() 
##    addMarkers(lng=-120.912, lat=56.1938, popup="Site C")
m  # Print the map

setView(lng=-120.912, lat=56.1938, zoom=16)
m

OpenTopoMap
Esri.WorldStreetMap
Wikimedia ## good for roads
m %>% addProviderTiles(providers$Esri.WorldImagery)
m %>% addProviderTiles(providers$Esri.NatGeoWorldMap)
m %>% addProviderTiles(providers$Stamen.Watercolor)


library(rgdal)
footprint <- readOGR("shp/BB_2017_ProjectFootprint.shp", layer = "BB_2017_ProjectFootprint")
plot(footprint)
summary(footprint)
newcrs = "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
footprintLL <- spTransform(footprint, newcrs)
summary(footprintLL)

t <- leaflet(footprint)
t

m <- leaflet(options = leafletOptions(minZoom = 5, maxZoom = 30)) %>% 
      addTiles(group = "OSM (default)")  %>%   
      addProviderTiles(providers$Esri.WorldStreetMap, group = "Street Map") %>%    
      addProviderTiles(providers$Wikimedia, group = "Wikimedia") %>%
      addProviderTiles(providers$Esri.WorldImagery, group = "Imagery") %>%
      addRectangles(
        lng1=-122.032, lat1=55.85,
        lng2=-120.64, lat2=56.37,
        fillColor = "transparent"
        ) %>%
# addMarkers of addPopups  
      addMarkers(lng=-120.912, lat=56.1938, popup="Site C", labelOptions(sticky=FALSE)) %>%
      # Layers control
      addLayersControl(
        baseGroups = c("OSM (default)", "Street Map", "Wikimedia", "Imagery"),
        options = layersControlOptions(collapsed = FALSE))

m

# Use this to set an initial view. 
m %>% setView(m, lng=-120.912, lat=56.1938, zoom=8)

# Add measurement tool
m %>% addMeasure(primaryLengthUnit = "metres",
                 primaryAreaUnit = "hectares")

# Add minimap
m %>% addMiniMap(tiles = providers$Wikimedia,
                toggleDisplay = TRUE)
```

# MapView

A wrapper for Leaflet. Automates many functions.Good for intermediate viewing of data, not necessarily for presentation quality.

```{r}
library(tidyverse)
library(mapview)

dat <- read_csv("C:/Users/jeff.matheson/Documents/R Working/Spatial/SiteC/SiteCsong.csv")

mapview(dat, xcol="Longitude", ycol="Latitude", crs=4269)

library(rgdal)
footprint <- readOGR("C:/Users/jeff.matheson/Documents/R Working/Spatial/SiteC/BB_2017_ProjectFootprint.shp", layer = "BB_2017_ProjectFootprint")
plot(footprint)
summary(footprint)

newcrs = 4269

newcrs = "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"

footprintLL <- spTransform(footprint, newcrs)

summary(footprintLL)

        
```

```{r}
# Add graticule
m %>% addGraticule(interval = 1, group = "Graticule") %>%
  addLayersControl(overlayGroups = c("Graticule"),
    options = layersControlOptions(collapsed = FALSE))

m %>% addMarkers(
  clusterOptions = markerClusterOptions()
)


library(htmlwidgets)


```

# Shiny

```{r}
library(shiny)

ui <- fluidPage()
server <- function(input, output){}
shinyApp(ui=ui, server = server)


```

# Google Maps API

```{r}
register_google(key = "AIzaSyDq1pZGYfF1PmyxxvWvLPW22TH7dAOkt90", write = TRUE)
has_google_key()
google_key()
hdf <- get_map("houston, texas")
ggmap(hdf, extent = "normal")
ggmap(hdf) # extent = "panel", note qmap defaults to extent = "device"
ggmap(hdf, extent = "device")
```
